# helmfile.yaml
repositories:
  # - name: nvdp
  #   url: https://nvidia.github.io/k8s-device-plugin
  - name: eks-charts
    url: https://aws.github.io/eks-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:

  - name: aws-load-balancer-controller
    namespace: kube-system
    chart: eks-charts/aws-load-balancer-controller
    values:
      - manifests/aws-load-balancer-controller-values.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack



  # # CRDs - bump `version` deliberately; CRD upgrades sometimes need manual migration
  # - name: karpenter-crd
  #   namespace: karpenter
  #   createNamespace: true
  #   chart: oci://public.ecr.aws/karpenter/karpenter-crd
  #   version: "1.6.1"
  #
  # # Controller
  # - name: karpenter
  #   namespace: karpenter
  #   chart: oci://public.ecr.aws/karpenter/karpenter
  #   version: "1.6.1"
  #   needs:
  #     - karpenter/karpenter-crd
  #   values:
  #     - karpenter-values.yaml
  #
  # - name: nvidia-device-plugin
  #   namespace: kube-system
  #   chart: nvdp/nvidia-device-plugin
  #   values:
  #     - tolerations:
  #         - key: nvidia.com/gpu
  #           operator: Equal
  #           value: "true"
  #           effect: NoSchedule
  #       affinity:
  #         nodeAffinity:
  #           requiredDuringSchedulingIgnoredDuringExecution:
  #             nodeSelectorTerms:
  #               - matchExpressions:
  #                   - key: workload
  #                     operator: In
  #                     values: ["gpu"]
